train_data_path: "data_raw/heart.csv"
data_for_pred_path: "data_raw/data_for_pred.csv"
predictions_path: "models/predictions.csv"
model_path: "models/model.pkl"
transformer_path: "models/transformer.pkl"
metric_path: "models/metrics.json"
split_params:
  test_size: 0.2
  random_state: 321
train_params:
  model_type: "RandomForestClassifier"
  max_depth: 10
  n_estimators: 100
  n_jobs: -1
features_params:
  categorical:
    - 'sex'
    - 'cp'
    - 'fbs'
    - 'restecg'
    - 'exang'
    - 'slope'
    - 'ca'
    - 'thal'
  numerical:
    - 'age'
    - 'trestbps'
    - 'chol'
    - 'thalach'
    - 'oldpeak'
  target: 'target'